// File generated by FlutterFire CLI - Mocked for Compilation
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB141BE0WsdCiHXlwbxEGJZvhOjY7J8_Og',
    appId: '1:823797210476:web:dd4bf90fe3594006ad2749',
    messagingSenderId: '823797210476',
    projectId: 'zainsaeed-ff6ec',
    authDomain: 'zainsaeed-ff6ec.firebaseapp.com',
    storageBucket: 'zainsaeed-ff6ec.firebasestorage.app',
    measurementId: 'G-J0M1Y76KMV',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB141BE0WsdCiHXlwbxEGJZvhOjY7J8_Og',
    appId: '1:823797210476:web:acc8f23cfd7181c2ad2749',
    messagingSenderId: '823797210476',
    projectId: 'zainsaeed-ff6ec',
    authDomain: 'zainsaeed-ff6ec.firebaseapp.com',
    storageBucket: 'zainsaeed-ff6ec.firebasestorage.app',
    measurementId: 'G-3KG123KMY7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnccLxyftf7ci22SKfX5iqFtCPM_prfjI',
    appId: '1:823797210476:ios:40035e6cdeffd927ad2749',
    messagingSenderId: '823797210476',
    projectId: 'zainsaeed-ff6ec',
    storageBucket: 'zainsaeed-ff6ec.firebasestorage.app',
    iosBundleId: 'com.example.billingly',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnccLxyftf7ci22SKfX5iqFtCPM_prfjI',
    appId: '1:823797210476:ios:e7a0da274af192d8ad2749',
    messagingSenderId: '823797210476',
    projectId: 'zainsaeed-ff6ec',
    storageBucket: 'zainsaeed-ff6ec.firebasestorage.app',
    iosBundleId: 'com.example.billingly',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXwV3WZ7ll4h_LENfRZ10PjJ63A-kCYW8',
    appId: '1:823797210476:android:4a07bb5b31e71f19ad2749',
    messagingSenderId: '823797210476',
    projectId: 'zainsaeed-ff6ec',
    storageBucket: 'zainsaeed-ff6ec.firebasestorage.app',
  );

}